server:
  port: ${PORT:8081}
spring:
  application:
    name: spring-boot-api-gateway-demo
  cloud:
    gateway:
      routes:
        - id: spring-boot-eureka-client-demo
          uri: lb://spring-boot-eureka-client-demo
          predicates:
            - Path=/greetings/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
